[package]
name = "procon"
version = "0.1.0"
authors = ["imulan <cp.imulan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "procon"
path = "main.rs"
